name: lint my project
on:
  push:
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: lint
    - name: Check out repository 
      uses: actions/checkout@v2
    - name: lint
      run: make lint
